version: '2.1'

services:
  app_under_test:
    image: govukpay/${IMAGE}:${TAG}
    env_file: ${WORKSPACE}/test/cypress/test.env
    environment:
      PORT: 3000
      CONNECTOR_URL: http://stub:8080
      DIRECT_DEBIT_CONNECTOR_URL: http://stub:8080
      PUBLIC_AUTH_BASE: http://stub:8080
      PUBLIC_AUTH_URL: http://stub:8080/v1/frontend/auth
      ADMINUSERS_URL: http://stub:8080
      PRODUCTS_URL: http://stub:8080
    mem_limit: 1G
    logging:
      driver: "json-file"

  cypress:
    image: govukpay/cypress:6
    environment:
      CYPRESS_baseUrl: http://app_under_test:3000
      MOUNTEBANK_URL: http://stub:2525,
      MOUNTEBANK_IMPOSTERS_PORT: 8080
    volumes:
      - ${WORKSPACE}/test/cypress:/app/test/cypress
      - ${WORKSPACE}/cypress.json:/app/cypress.json
      - ${WORKSPACE}/node_modules:/app/node_modules
      - ${WORKSPACE}/test/fixtures:/app/test/fixtures
      - ${WORKSPACE}/app/models:/app/app/models
    logging:
      driver: "json-file"
    mem_limit: 2G

  stub:
    image: andyrbell/mountebank:1.16.0
    entrypoint:
      - "-p"
      - "2525:2525"
      - "-p"
      - "8080:8080"
    mem_limit: 1G
