version: '2.1'

services:
  app_under_test:
    image: govukpay/${IMAGE}:${TAG}
    env_file: ${WORKSPACE}/test/cypress/test.env
    environment:
      PORT: 3000
      CONNECTOR_URL: http://stub:8080
      DIRECT_DEBIT_CONNECTOR_URL: http://stub:8080
      PUBLIC_AUTH_BASE: http://stub:8080
      PUBLIC_AUTH_URL: http://stub:8080/v1/frontend/auth
      ADMINUSERS_URL: http://stub:8080
      PRODUCTS_URL: http://stub:8080
    mem_limit: 1G
    logging:
      driver: "json-file"

  cypress:
    image: govukpay/cypress:6
    environment:
      CYPRESS_baseUrl: http://app_under_test:3000
    volumes:
      - ${WORKSPACE}/test/cypress:/app/test/cypress
      - ${WORKSPACE}/cypress.json:/app/cypress.json
      - ${WORKSPACE}/node_modules:/app/node_modules
      - ${WORKSPACE}/test/fixtures:/app/test/fixtures
    logging:
      driver: "json-file"
    mem_limit: 2G

  stub:
    image: pactfoundation/pact-stub-server
    entrypoint:
      - "/app/pact-stub-server"
      - "-p"
      - "8080"
      - "-d"
      - "pacts"
    volumes:
      - ${WORKSPACE}/pacts:/app/pacts
    mem_limit: 1G
